/**
 * Export utilities module.
 * Handles GeoJSON, KML, and KMZ export formats beyond what DuckDB provides natively.
 */

/**
 * Trigger a file download in the browser.
 * @param {Blob|Uint8Array} data
 * @param {string} filename
 * @param {string} mimeType
 */
export function downloadData(data, filename, mimeType) {
  const blob = data instanceof Blob ? data : new Blob([data], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Build a GeoJSON FeatureCollection from an array of row objects.
 * @param {object[]} rows - Array of data row objects
 * @param {string} latCol - Column name for latitude
 * @param {string} lonCol - Column name for longitude
 * @returns {{ geojson: object, skipped: number }} GeoJSON FeatureCollection and count of skipped rows
 */
export function buildGeoJSON(rows, latCol, lonCol) {
  let skipped = 0;
  const features = rows
    .filter((row) => {
      const lat = parseFloat(row[latCol]);
      const lon = parseFloat(row[lonCol]);
      const valid = !isNaN(lat) && !isNaN(lon) && lat >= -90 && lat <= 90 && lon >= -180 && lon <= 180;
      if (!valid) skipped++;
      return valid;
    })
    .map((row) => {
      const lat = parseFloat(row[latCol]);
      const lon = parseFloat(row[lonCol]);

      // Build properties: all columns except internal _row_id
      const properties = {};
      for (const [key, val] of Object.entries(row)) {
        if (key !== '_row_id') {
          properties[key] = val;
        }
      }

      return {
        type: 'Feature',
        geometry: {
          type: 'Point',
          coordinates: [lon, lat],
        },
        properties,
      };
    });

  if (skipped > 0) {
    console.warn(`buildGeoJSON: skipped ${skipped} row(s) with invalid or missing coordinates.`);
  }

  return {
    geojson: { type: 'FeatureCollection', features },
    skipped,
  };
}

/**
 * Build a KML document string from an array of row objects.
 * @param {object[]} rows
 * @param {string} latCol
 * @param {string} lonCol
 * @param {string} [documentName='KYTC Roadway Data']
 * @returns {{ kml: string, skipped: number }}
 */
export function buildKML(rows, latCol, lonCol, documentName = 'KYTC Roadway Data') {
  let skipped = 0;
  const validRows = rows.filter((row) => {
    const lat = parseFloat(row[latCol]);
    const lon = parseFloat(row[lonCol]);
    const valid = !isNaN(lat) && !isNaN(lon);
    if (!valid) skipped++;
    return valid;
  });

  const placemarks = validRows
    .map((row, idx) => {
      const lat = parseFloat(row[latCol]);
      const lon = parseFloat(row[lonCol]);

      const extData = Object.entries(row)
        .filter(([key]) => key !== '_row_id' && key !== latCol && key !== lonCol)
        .map(
          ([key, val]) =>
            `      <Data name="${escapeXml(key)}"><value>${escapeXml(
              val != null ? String(val) : ''
            )}</value></Data>`
        )
        .join('\n');

      const name = row['Road_Name'] || row['Route'] || `Point ${idx + 1}`;

      return `    <Placemark>
      <name>${escapeXml(String(name))}</name>
      <Point>
        <coordinates>${lon},${lat},0</coordinates>
      </Point>
      <ExtendedData>
${extData}
      </ExtendedData>
    </Placemark>`;
    })
    .join('\n');

  if (skipped > 0) {
    console.warn(`buildKML: skipped ${skipped} row(s) with invalid or missing coordinates.`);
  }

  const kml = `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>${escapeXml(documentName)}</name>
    <description>Generated by KYTC Roadway Processor</description>
${placemarks}
  </Document>
</kml>`;

  return { kml, skipped };
}

/**
 * Build a KMZ (zipped KML) Blob from a KML string.
 * Requires JSZip to be loaded on the page.
 * @param {string} kmlContent
 * @returns {Promise<Blob>}
 */
export async function buildKMZ(kmlContent) {
  const JSZip = window.JSZip;
  if (!JSZip) {
    throw new Error('JSZip is not loaded. Cannot create KMZ file.');
  }
  const zip = new JSZip();
  zip.file('doc.kml', kmlContent);
  return zip.generateAsync({ type: 'blob', compression: 'DEFLATE' });
}

/**
 * Escape special XML characters in a string.
 */
function escapeXml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Suggest lat/lon column names from a list of column names.
 * Returns { latCol, lonCol } or null if not found.
 * @param {Array<{name: string, type: string}>} columns
 * @returns {{ latCol: string|null, lonCol: string|null }}
 */
export function suggestCoordColumns(columns) {
  const names = columns.map((c) => c.name);

  const latCandidates = [
    'latitude', 'lat', 'y', 'ylat', 'lat_y', 'latitude_y',
    'LATITUDE', 'LAT', 'Y', '_geojson_lat',
  ];
  const lonCandidates = [
    'longitude', 'lon', 'lng', 'x', 'xlon', 'lon_x', 'longitude_x',
    'LONGITUDE', 'LON', 'LNG', 'X', '_geojson_lon',
  ];

  const findCol = (candidates) => {
    // Exact match first
    for (const c of candidates) {
      if (names.includes(c)) return c;
    }
    // Case-insensitive partial match
    const lowerNames = names.map((n) => n.toLowerCase());
    for (const c of candidates) {
      const idx = lowerNames.indexOf(c.toLowerCase());
      if (idx !== -1) return names[idx];
    }
    // Partial substring match
    for (const n of names) {
      const nl = n.toLowerCase();
      if (candidates.some((c) => nl.includes(c.toLowerCase()))) return n;
    }
    return null;
  };

  return {
    latCol: findCol(latCandidates),
    lonCol: findCol(lonCandidates),
  };
}
